name = "noesya Hugo theme"
license = "MIT"
licenselink = "https://github.com/noesya/noesya-hugo-theme/blob/main/LICENSE"
description = "Hugo theme for noesya websites, based on Osuny"
homepage = "https://www.noesya.coop"
tags = []
features = []
min_version = "0.91.0"

[author]
  name = "noesya"
  homepage = "https://www.noesya.coop"
